spring.application.name=urlshortener
app.url.base-url=http://localhost:8080
app.frontend.url=http://localhost:3000
app.mail.from=noreply@test-nrw7gymr57jg2k8e.mlsender.net

# OPÇÃO 1: URI completa (RECOMENDADA)
spring.data.mongodb.uri=mongodb://admin:123@localhost:27017/shortenerdb?authSource=admin

# Configuração de índices
spring.data.mongodb.auto-index-creation=true

# GeoIP Configuration
geoip.database.path=src/main/resources/GeoLite2-City.mmdb

# Logging configuration
logging.level.desafiourl.urlshortener.service.GeoLocationService=INFO
logging.level.org.springframework.data.mongodb=DEBUG


# Configurações de Email - MailerSend
spring.mail.host=smtp.mailersend.net
spring.mail.port=587
spring.mail.username=MS_uZhYRx@test-nrw7gymr57jg2k8e.mlsender.net
spring.mail.password=mssp.n5QemGm.zr6ke4nqpde4on12.OOoOPo7
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Configurações do Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.check-template-location=true
spring.thymeleaf.cache=false